version: '3.7'

services:

 
  checker:
    image: koo5/checker:latest
    networks:
      - frontend
#    ports:
#      - 3000
    deploy:
      replicas: 1
      restart_policy:
        condition: any

 
  echo:
    image: koo5/echo:latest
    networks:
      - frontend
    ports:
      - 5001
    deploy:
      replicas: 1
      restart_policy:
        condition: any

 
  alertmanager:
    image: koo5/alertmanager:latest
    volumes:
      - "alertmanager_storage:/alertmanager"
      - "alertmanager_etc:/etc/alertmanager"
    networks:
      - frontend
    ports:
      - 9093:9093
    deploy:
      replicas: 1
      restart_policy:
        condition: any


  karma:
    image: koo5/karma:latest
    volumes:
      - "./karma/karma.yaml:/karma.yaml"
    environment:
      ALERTMANAGER_URI: "http://alertmanager:9093"
    networks:
      - frontend
    ports:
      - "9094:8080"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    depends_on:
      - alertmanager

 
  demonitor:
    image: koo5/demonitor:latest
    volumes:
      - "./demonitor/config.aml:/usr/src/app/demonitor/config.aml"
      - "jsipfs:/usr/src/app/ipfs"
      - "orbitdb:/usr/src/app/orbitdb"
    environment:
      ALERTMANAGER_URL: "http://alertmanager:9093"
#      DEBUG: "*"
    networks:
      - frontend
    ports:
      - "3223:3223"
      - "4002:4002"
      - "4003:4003"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    depends_on:
      - karma
      - ipfs

 
  ipfs:
    image: ipfs/go-ipfs:latest
    volumes:
      - ipfs_staging:/export
      - ipfs_data:/data/ipfs
    #environment:
      #IPFS_SWARM_KEY_FILE: /run/secrets/swarm.key
    networks:
      - frontend
    ports:
      - "4001:4001"
      - "5002:8080"
      - "5001:5001"
    #secrets:
    #  - IPFS_SWARM_KEY_FILE
    command: daemon --migrate=true --enable-pubsub-experiment


networks:
  frontend:


volumes:
  orbitdb:
  jsipfs:
  ipfs_staging:
  ipfs_data:
  alertmanager_storage:
  alertmanager_etc:


#secrets:
#  IPFS_SWARM_KEY_FILE:
#    file: secrets/swarm.key

