version: '3.7'

services:

  alertmanager:
    image: quay.io/prometheus/alertmanager:v0.22.0
    networks:
      - frontend
    ports:
      - 9093:9093
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  karma:
    image: koo5/configurable_karma:latest
    volumes:
      - "./configurable_karma/karma.yaml:/karma.yaml"
    environment:
      ALERTMANAGER_URI: "http://alertmanager:9093"
    networks:
      - frontend
    ports:
      - "9094:8080"
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  demonitor:
    image: koo5/demonitor:latest
    volumes:
      - "./demonitor/config.aml:/usr/src/app/config.aml"
      - "ipfs:/usr/src/app/ipfs"
      - "orbitdb:/usr/src/app/orbitdb"
    environment:
      ALERTMANAGER_URL: "http://alertmanager:9093"
    networks:
      - frontend
    ports:
      - "3223:3223"
    deploy:
      replicas: 1
      restart_policy:
        condition: any


networks:
  frontend:


volumes:
  ipfs:
  orbitdb:


