route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  #receiver: 'web.hook'




# this goes to the example "echo" service for no reason really

#receivers:
#- name: 'web.hook'
#  webhook_configs:
#  - url: 'http://echo:6006/'




# mute all info alerts when a critical alert exists

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'info'
