version: '3.7'

services:

  am:
    image: quay.io/prometheus/alertmanager:v0.22.0
    networks:
      - frontend
    ports:
      - 9093:9093
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  karma:
    image: koo5/configurable_karma:latest
    volume:
      - "./alertmanager/karma.yaml:/karma.yaml"
#    environment:
#      - ALERTMANAGER_URI=http://am:9093
    networks:
      - frontend
    ports:
      - "9094:8080"
    deploy:
      replicas: 1
      restart_policy:
        condition: any


networks:
  frontend:
